version: "3.9"
services:
  code:
    image: code
    container_name: code
    ports:
      - "5000:5000"

  api:
    image: api
    container_name: api
    ports:
      - "5050:5050"

  db:
    image: mongo:latest
    container_name: mongo
    ports:
      - "6000:6000"
